config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/search', to: 'search_patients#search'
  get '/payment', to: 'get_payment#index'
  
  resources :get_doctor_patients, only: [:index]
  resources :in_patients, param: :novem_digit, only: [:create]
  resources :out_patients, param: :novem_digit, only: [:create]
  root to: "static_pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/confirm_recovery.rb
class ConfirmRecovery < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/examination.rb
class Examination < ApplicationRecord 
end

app/models/examination_diagnosis.rb
class ExaminationDiagnosis < ApplicationRecord
end

app/models/has_next_examination.rb
class HasNextExamination < ApplicationRecord
end

app/models/in_patient.rb
class InPatient < ApplicationRecord
  self.primary_key = :novem_digit
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :gender, presence: true
  validates :dob, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true
  validates :date_of_admission, presence: true
  validates :sickroom, presence: true
  validates :fee, presence: true
  validates :nurse_id, presence: true
end



# imma need doctor_id, full_name, 

app/models/in_patient_diagnosis.rb
class InPatientDiagnosis < ApplicationRecord
end

app/models/medication.rb
class Medication < ApplicationRecord
end

app/models/medication_effect.rb
class MedicationEffect < ApplicationRecord
end

app/models/out_patient.rb
class OutPatient < ApplicationRecord
  self.primary_key = :novem_digit
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :gender, presence: true
  validates :dob, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true
end

app/models/phone.rb
class Phone < ApplicationRecord
end

app/models/provider.rb
class Provider < ApplicationRecord
end

app/models/treatment.rb
class Treatment < ApplicationRecord
end

app/models/use_treatment_medication.rb
class UseTreatmentMedication < ApplicationRecord
end

app/controllers/in_patients_controller.rb
class InPatientsController < ApplicationController
  @@identifier = 10
  def create
    @@identifier += 1
    novem = "0"
    until novem.length == (9 - @@identifier.to_s.length)
      novem += "0"
    end
    novem += @@identifier.to_s
    fname = params["first_name"]
    lname = params["last_name"]
    gender = params["gender"]
    dob = params["dob"]
    phoneno = params["phone_no"]
    addr = params["address"]
    doa = params["doa"]
    sickroom = params["sickroom"].to_i
    fee = params["fee"].to_f
    nid = params["nurse"].to_i
    raw = "insert into in_patients values (
      'IP',
      '#{novem}',
      '#{fname}',
      '#{lname}',
      '#{gender}',
      '#{dob}',
      '#{phoneno}',
      '#{addr}',
      '#{doa}',
      '#{sickroom}',
      '#{fee}',
      '#{nid}'
);"
    ActiveRecord::Base.connection.execute(raw)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/get_payment_helper.rb
module GetPaymentHelper
end

app/helpers/in_patients_helper.rb
module InPatientsHelper
end

app/helpers/out_patients_helper.rb
module OutPatientsHelper
end

app/helpers/search_patients_helper.rb
module SearchPatientsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/in_patients/_new_inpatient_form.html.erb
<h1>New In-patient Registration</h1>
<%= form_with url: in_patients_url, method: "post" do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name  %>
  <br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br>
  <%= f.label :phone_no, "Phone number" %>
  <%= f.telephone_field :phone_no, pattern: "[0-9]{3}-[0-9]{3}-[0-9]{4}" %>
  <br>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <br>
  <%= label_tag 'gender' %>
  <%= select_tag 'gender', raw("<option value=\"M\">Male</option><option value=\"F\">Female</option>") %>
  <br>
  <%= f.label :dob, "Date of Birth" %>
  <%= f.date_field :dob %>
  <br>
  <%= label_tag :sickroom %>
  <%= select_tag 'sickroom', raw("<option>4161</option><option>2005</option><option>4235</option><option>4346</option><option>3725</option><option>3385</option><option>4665</option><option>4165</option><option>2283</option><option>4195</option>") %>
  <br>
  <%= f.label :doa, "Date of Admission" %>
  <%= f.date_field :doa %>
  <br>
  <%= f.label :fee %>
  <%= f.number_field :fee, step: 0.5 %>
  <br>
  <%= label_tag 'nurse' %>
  <%= select_tag 'nurse', options_for_select(Employee.where('job_type = ?', 'nurse').collect{ |p| ["#{p.first_name+' '+p.last_name}", p.id ] }) %>
  <br>
  <%= f.submit "Register" %>
<% end %>


<%# 2020-01-06 21:18:22,2019-11-27 08:25:22,2019-12-01 21:02:11,2020-01-01 04:13:44,2020-01-08 10:26:35,2020-01-03 19:06:21,2019-01-03 20:47:34,2019-12-10 14:08:12,2020-01-08 04:27:33,2019-12-09 05:44:32

2020-09-14 13:33:39,2019-12-15 09:39:32,2020-02-03 19:13:26,2020-10-05 02:00:00,2020-04-26 03:56:55,2020-10-05 08:32:17,2019-11-29 13:45:35,2020-04-04 14:25:42,2020-04-08 21:21:42,2020-02-19 17:09:08

4,8,2,8,10,2,2,10,8,10

000000001,000000002,000000003,000000004,000000005,000000006,000000007,000000008,000000009,000000010 %>